#!/usr/bin/env bash

# Replace 'your-instance-id' with your EC2 instance ID
INSTANCE_ID="i-0153b3925fbd4cec5"

# Check if today is a weekday (Monday to Friday)
if [ $(date +%u) -ge 1 ] && [ $(date +%u) -le 5 ]; then
    # Check if the instance is running
    INSTANCE_STATE=$(aws ec2 describe-instance-status --instance-ids $INSTANCE_ID --query 'InstanceStatuses[0].InstanceState.Name' --output text)
    
    if [ "$INSTANCE_STATE" != "running" ]; then
        # Start the instance
        aws ec2 start-instances --instance-ids $INSTANCE_ID > /dev/null 2>&1
        echo "EC2 instance $INSTANCE_ID is starting..."
    else
        echo "EC2 instance $INSTANCE_ID is already running."
    fi
else
    echo "Today is not a weekday. No action needed."
fi

