#! /bin/sh

# Monitor setup
export INTERNAL_MONITOR="$(xrandr -q | grep -o 'eDP-\?1')"
export EXTERNAL_MONITOR="$(xrandr -q | grep -o 'HDMI-\?2')"
xrandr --output $INTERNAL_MONITOR --primary --mode 1920x1080 --rotate normal --output $EXTERNAL_MONITOR --mode 1920x1080 --rotate normal --right-of $INTERNAL_MONITOR
bspc monitor $INTERNAL_MONITOR -d 5 6 7 8
bspc monitor $EXTERNAL_MONITOR -d 1 2 3 4

# Start UI thingies
xrdb ~/.Xresources &
sh ~/.local/scripts/launch-polybar.sh & 
picom --experimental-backends &
feh --bg-fill ~/Wallpaper/wallpaper.png &

# Swallowing
pgrep bspswallow || ~/.local/scripts/bspswallow &

# Remove x cursor
xsetroot -cursor_name left_ptr & 

# Configs
bspc config border_width 5
bspc config window_gap 15
bspc config top_padding 50
bspc config bottom_padding 5
bspc config left_padding 10
bspc config right_padding 10

bspc config normal_border_color "#2E3440"
bspc config active_border_color "#2E3440"
bspc config focused_border_color "#88C0D0"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus none
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Autostart
xinput --set-prop "Logitech G102 Prodigy Gaming Mouse" "Coordinate Transformation Matrix" 1.25 0 0 0 1.25 0 0 0 1 &
sxhkd -m 1 &
setxkbmap -layout us,ru -variant dvorak-intl, -option grp:alt_shift_toggle &
