#! /bin/sh

# Monitor setup
export INTERNAL_MONITOR="$(xrandr -q | grep -o 'eDP-\?1')"
export EXTERNAL_MONITOR="$(xrandr -q | grep -o 'HDMI-\?2')"
xrandr --output eDP1 --primary --mode 1920x1080 --scale 0.85x0.85 --output HDMI2 --mode 1920x1080 --right-of eDP1
bspc monitor $EXTERNAL_MONITOR -d 1 2 3 4
bspc monitor $INTERNAL_MONITOR -d 5 6 7 8

# Start UI thingies
xrdb ~/.Xresources &
sh ~/.local/scripts/launch-polybar.sh & 
picom --experimental-backends &
feh --bg-fill ~/Wallpaper/wallpaper.png &

# Swallowing
pgrep bspswallow || ~/.local/scripts/bspswallow &

# Remove x cursor
xsetroot -cursor_name left_ptr & 

# Configs
bspc config border_width 4
bspc config window_gap 15
bspc config top_padding 50
bspc config bottom_padding 5
bspc config left_padding 10
bspc config right_padding 10

bspc config normal_border_color "#3B4252"
bspc config active_border_color "#3B4252"
bspc config focused_border_color "#88C0D0"

bspc config split_ratio          0.5

bspc config click_to_focus none
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Application rules
bspc rule -a Emacs state=tiled

# Autostart
xinput --set-prop "Logitech G102 Prodigy Gaming Mouse" "Coordinate Transformation Matrix" 1.25 0 0 0 1.25 0 0 0 1 &
xinput --set-prop "Kensington Expert Mouse" "Coordinate Transformation Matrix" 0.1 0 0 0 0.1 0 0 0 1 &
sxhkd -m 1 &
setxkbmap -layout us,ru -variant , -option grp:alt_shift_toggle &
